Add initial setup code for table.
digitalbazaar/bedrock-quasar-table pull request #1
Opened 2020-03-06 15:58 UTC by JoshDunnDev

2020-03-09 13:46 UTC, mattcollier approved these changes

2020-03-09 14:34 UTC, gannan08 requested changes
The name of QTable props should be preserved. Ideally, we should be extending the component such that we have access to the same QTable API; props and all.

2020-03-09 14:34 UTC, gannan08 commented on BrQTable.vue
> +    tableColumns: {
```suggestion
    columns: {
```

2020-03-09 14:34 UTC, gannan08 commented on BrQTable.vue
> +    loadingData: {
```suggestion
    loading: {
```

2020-03-09 14:34 UTC, gannan08 commented on BrQTable.vue
> +    tableData: {
```suggestion
    data: {
```

2020-03-11 18:44 UTC, gannan08 approved these changes
LGTM. The renaming of the props will cause any dependent library to break. We will need PRs for anything using br-q-table.

2020-03-11 18:46 UTC, JoshDunnDev commented
> LGTM. The renaming of the props will cause any dependent library to break. We will need PRs for anything using br-q-table.

Well this needs to be merged into master so we can properly make PRs.

2020-03-11 18:48 UTC, merged